version: "3.8"

services:
  nginx:
    image: t3tech/7t4-proxy
    deploy:
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    networks:
      - 7t4proxy
    volumes:
      - /mnt/gluster/www:/usr/share/nginx/html
      - /mnt/gluster/nginx:/etc/nginx

#  php:
#    image: andrewnk/base-alpine-php
#    container_name: php
#    networks:
#      - web
#    volumes:
#      - app:/var/www/html

networks:
  7t4proxy:
    driver: overlay
